### ISSUE TITLE
How can we use this module?

### ISSUE THREAD

**Issue by jviotti** [kevinsawicki/electabul#1]
I came across this project, and would love to get Istanbul running on Etcher (https://github.com/resin-io/etcher/). 

Do you mind expanding a bit more on how can we use this module? I can see that it produces an instrumented asar, however how do we make use of this asar to generate the typical Istanbul coverage HTML output?

We're using `electron-mocha` for both the main and the renderer process in case that matters.

**Comment by mykter** [comment]
From Electron's package.json:
```
"coverage": "npm run instrument-code-coverage && npm test -- --use_instrumented_asar",
"instrument-code-coverage": "electabul instrument --input-path ./lib --output-path ./out/coverage/electron.asar",
```

The [entire commit](https://github.com/electron/electron/commit/ad07a20d9a356671073c2ca7785562b409d5c100) to switch to using electabul for coverage isn't that large - I suspect it was written specifically for this use case?

However, electron already had an asar-based testing framework for testing `electron.asar`. It's not obvious to me that it would be easy to convert an app that is tested using mocha in the traditional way to one that tests using an asar. But I'm no electron expert!

Trying to run the electron coverage tests locally and it fails with:
```
> electabul instrument --input-path ./lib --output-path ./out/coverage/electron.asar

Failed to parse file: /tmp/electron/lib/browser/guest-window-manager.js
```
Looks like electabul is expecting an older version of javascript sources. Perhaps it's no longer even being used in Electron.

**Comment by jviotti** [comment]
Closing stale issues
